#!/bin/bash

index='target/index.html'

# paranoic rm
rm -rf target
mkdir target
cp -r pdfs target/pdfs

cat << EOF > "$index"
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width" />
        <title>Math 105 Notes</title>
        <style>
            html, body{
                margin: 0;
                padding: 0;
                font-size: 1.2em;
            }
            
            body{
                margin: 0 auto;
                max-width: 36em;
                padding: 50px;
            }

            h1, p{
                text-align: center;
            }

            a{
                color: black;
            }

            .date {
                font-size: .8rem;
            }
        </style>
    </head>
    <body>
        <h1>Math 105 Notes</h1>
        <p>Shane McDonough for Professor Ho</p>
        <p>last updated: $(date "+%m/%d/%y")</p>
        <ol start="0">
EOF

for file in pdfs/*; do
    base="$(basename -s .pdf "$file")"
    date="${base:2:2}/${base:4:2}/${base::2}"
    title="${base:6}"
    echo "<li><a href=\"$file\">$title</a> <span class=date>$date</span></li>"
done >> "$index"
